### ISSUE TITLE
Ordering of file concatenation in Sheldon#build is undefined

### ISSUE THREAD

**Issue by dvjones89** [dvjones89/sheldon#32]
Recent builds of `master` have been failing on Travis.ci, but consistently pass when run locally.
Here's the Travis output for the failing spec:
```
Failures:
  1) Builder build for a directory with multiple config_ files should create a master config file
     Failure/Error: expect(File.read(abs_master_path)).to eq "hello\nworld\n"
     
       expected: "hello\nworld\n"
            got: "world\nhello\n"
     
       (compared using ==)

     # ./spec/sheldon/builder_spec.rb:31:in `block (4 levels) in <top (required)>'
```
As you can see, we're expecting "hello world" but `Sheldon#build` is outputting "world hello". Looking at [the source code](https://github.com/dvjones89/sheldon/blob/c624b2939a1880f859a205529a23664c370fde3d/lib/sheldon/builder.rb#L5), the ordering of file concatenation depends solely on the behaviour of Ruby's Dir.glob, which can (and indeed does) vary between hosts.

Sheldon should be updated to first sort `config_` files alphabetically, before concatenating them together, thus making the ordering of files consistent across different environments.
